# Generated by Django 3.2.13 on 2022-05-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titreoperation', models.TextField(max_length=200)),
                ('entreprise', models.TextField(max_length=50, null=True)),
                ('annee_de_livraison', models.TextField(max_length=10, null=True)),
                ('ville', models.TextField(max_length=50)),
                ('mandataire', models.TextField(max_length=50, null=True)),
                ('nombre_de_lots', models.IntegerField(null=True)),
                ('ppi', models.TextField(max_length=20)),
                ('lycee', models.TextField(max_length=50)),
                ('notification_du_marche', models.TextField(max_length=20, null=True)),
                ('codeuai', models.TextField(max_length=20)),
                ('longitude', models.TextField(max_length=50, null=True)),
                ('etat_d_avancement', models.TextField(max_length=50)),
                ('montant_des_ap_votes_en_meu', models.TextField(max_length=50, null=True)),
                ('cao_attribution', models.TextField(max_length=20, null=True)),
                ('latitude', models.TextField(max_length=50, null=True)),
                ('maitrise_d_oeuvre', models.TextField(max_length=50, null=True)),
                ('mode_de_devolution', models.TextField(max_length=50, null=True)),
                ('annee_d_individualisation', models.TextField(max_length=10, null=True)),
                ('enveloppe_prev_en_meu', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
