# Generated by Django 3.2.13 on 2022-05-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_test_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscordUser',
            new_name='Investment',
        ),
    ]
